# Generated by Django 6.0.5 on 2026-05-24 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_index', models.IntegerField(help_text='0-based row number in the source CSV file')),
                ('raw_data', models.JSONField(help_text='Original CSV row stored as-is. Never modified after insert.')),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('suspicious', 'Suspicious'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked')], db_index=True, default='pending', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.uploadbatch')),
            ],
            options={
                'ordering': ['batch', 'row_index'],
                'unique_together': {('batch', 'row_index')},
            },
        ),
    ]
