# Generated by Django 6.0.5 on 2026-05-24 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue_code', models.CharField(db_index=True, max_length=100)),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], db_index=True, max_length=20)),
                ('field_name', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='ingestion.rawrecord')),
            ],
            options={
                'ordering': ['severity', 'issue_code'],
            },
        ),
    ]
