# Generated by Django 6.0.5 on 2026-05-24 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type_code', models.CharField(db_index=True, max_length=50)),
                ('record_date', models.DateField(blank=True, null=True)),
                ('facility_code', models.CharField(blank=True, max_length=100)),
                ('quantity_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=20)),
                ('co2e_kg', models.DecimalField(blank=True, decimal_places=4, help_text='CO2 equivalent in kg. Computed from emission factors at normalization time.', max_digits=15, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=100)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('material_code', models.CharField(blank=True, max_length=100)),
                ('meter_id', models.CharField(blank=True, max_length=100)),
                ('consumption_kwh', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('tariff', models.CharField(blank=True, max_length=100)),
                ('billing_start', models.DateField(blank=True, null=True)),
                ('billing_end', models.DateField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=100)),
                ('trip_type', models.CharField(blank=True, max_length=50)),
                ('departure_airport', models.CharField(blank=True, max_length=3)),
                ('arrival_airport', models.CharField(blank=True, max_length=3)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cabin_class', models.CharField(blank=True, max_length=50)),
                ('expense_amount_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('normalized_at', models.DateTimeField(auto_now_add=True)),
                ('normalization_notes', models.TextField(blank=True)),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingestion.rawrecord')),
            ],
            options={
                'ordering': ['-normalized_at'],
            },
        ),
    ]
