# Generated by Django 6.0.5 on 2026-05-24 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('flag', 'Flag for Review')], max_length=20)),
                ('analyst_name', models.CharField(help_text='Analyst who made this decision. Plain string in prototype.', max_length=255)),
                ('note', models.TextField(blank=True)),
                ('acted_at', models.DateTimeField(auto_now_add=True)),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_actions', to='ingestion.rawrecord')),
            ],
            options={
                'ordering': ['-acted_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(db_index=True, help_text="e.g., 'raw_record', 'upload_batch'", max_length=50)),
                ('entity_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(help_text="e.g., 'status_changed', 'batch_uploaded', 'record_locked'", max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('actor', models.CharField(blank=True, help_text="Analyst name or 'system' for automated events", max_length=255)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='review_audi_entity__2731fb_idx')],
            },
        ),
    ]
