# Generated by Django 6.0.5 on 2026-05-24 11:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('sap_fuel', 'SAP Fuel & Procurement'), ('utility_elec', 'Utility Electricity'), ('corporate_travel', 'Corporate Travel')], max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('scope', models.SmallIntegerField(choices=[(1, 'Scope 1'), (2, 'Scope 2'), (3, 'Scope 3')])),
            ],
            options={
                'ordering': ['scope', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=500)),
                ('uploaded_by', models.CharField(help_text='Analyst name or email. Not linked to auth user in this prototype.', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.client')),
                ('source_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='core.sourcetype')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
